print("Hello world")
print("Fred went to the store.", end="***")
print("Fred bought", "eggs", "bacon", "milk", "\n")
print("Fred asked asked, \'How much does this cost?\'")
print("About 5 \t\t\t\t dollars")