first_name = input("Type a first name: ")
last_name = input ("Type a last name: ")
gender = input("Is this person a him or her? ")
gender2 = input("Is this person a he or she? ")
family_role = input("Youngest, middle, or oldest (of the children)? ")
adjective1 = input("Type an adjective: ")
adjective2 = input("Type another adjective: ")
adjective3 = input ("Type another adjective: ")
infinitive1 = input("Type an infinitive: ")
noun1 = input("Type a noun: ")
noun2 = input("Type a plural noun: ")
number1 = input("Type a number: ")
superlative1 = input("Type a superlative: ")
number2 = input("type a number: ")
verb1 = input("Type a verb: ")
verb2 = input("Type another verb: ")
number3 = input("Type a number: ")
adjective4 = input("Type an adjective: ")
adjective5 = input("Type another adjective: ")
noun3 = input("Type a noun: ")
noun4 = input("Type another noun: ")
noun5 = input("Type yet another noun: ")

print(first_name," ", last_name, ", ", adjective1, ", ", adjective2, ", and ", adjective3, " with a comfortable ", noun1, " and happy disposition, seemed ", infinitive1, " some of the ", superlative1, sep="")
print(noun2, " of existence; and had lived nearly ", number1, " years in the world with very little to ", verb1, " or ", verb2," ", gender, ".", sep="")
print(gender2, " was the ", family_role, " of the, ", number3, " children of a most, ", adjective4, adjective5, noun3, "; and had, in consequence of, ", gender, " sister's marriage,", sep="")
print("been the master of ", gender, noun4, "from a very early period.", gender, noun5, " had died too long ago for her to have more than an indistinct remembrance of the caresses;")
print("and her place had been supplied by an excellent woman as governess, who had fallen little short of a mother in affection.")